import type { ValuationWorkspace } from '@efm/contracts'
import { valuationsApi } from '../../services/valuations'
import { countdownCopy, submissionStateCopy, validateValuationInput, valuationInputState, valuationPlayerView, valuationSummary, type ValuationPlayerView } from './valuation.viewmodel'

Page({
  data: { state: 'loading' as 'loading'|'loaded'|'error', errorMessage: '', teamId: '', workspace: null as ValuationWorkspace|null, players: [] as ValuationPlayerView[], countdown: '', submissionCopy: '', summary: { changedCount: 0, unchangedCount: 0, exceededCount: 0, missingCount: 0, complete: false }, editable: false, saving: false, publishing: false },
  onLoad(options: { teamId?: string }) { if (!options.teamId) this.setData({ state: 'error', errorMessage: '球队参数缺失' }); else { this.setData({ teamId: options.teamId }); void this.loadPage() } },
  async loadPage() { try { const workspace = await valuationsApi.workspace(this.data.teamId); const players = workspace.players.map(valuationPlayerView); this.setData({ state: 'loaded', workspace, players, countdown: countdownCopy(workspace), submissionCopy: submissionStateCopy(workspace), summary: valuationSummary(players), editable: workspace.window.state === 'OPEN' && !['PENDING_REVIEW', 'PUBLISHED', 'APPROVED'].includes(workspace.submission?.status ?? '') }) } catch { this.setData({ state: 'error', errorMessage: '身价工作区加载失败，请稍后重试' }) } },
  onValueInput(event: WechatMiniprogram.Input) { const index = Number(event.currentTarget.dataset.index); const players = [...this.data.players]; const current = players[index]; if (!current) return; players[index] = { ...current, inputValue: event.detail.value, changeState: valuationInputState(event.detail.value, current) }; this.setData({ players, summary: valuationSummary(players) }) },
  async saveDraft() { if (this.data.saving || !this.data.workspace) return; const error = this.localError(); if (error) return void wx.showToast({ title: error, icon: 'none' }); this.setData({ saving: true }); try { const submission = await valuationsApi.saveDraft(this.data.teamId, { windowId: this.data.workspace.window.id, expectedVersion: this.data.workspace.submission?.version ?? 1, items: this.data.players.map((player) => ({ snapshotId: player.snapshotId, proposedValueMinor: Number(player.inputValue) })) }); this.setData({ workspace: { ...this.data.workspace, submission }, submissionCopy: '草稿已保存' }); wx.showToast({ title: '草稿已保存', icon: 'success' }) } catch { wx.showToast({ title: '草稿保存失败', icon: 'none' }) } finally { this.setData({ saving: false }) } },
  async publish() { if (this.data.publishing || !this.data.workspace) return; const error = this.localError(); if (error) return void wx.showToast({ title: error, icon: 'none' }); const confirmed = await new Promise<boolean>((resolve) => wx.showModal({ title: '确认发布整批身价？', content: `修改 ${this.data.summary.changedCount} 人，沿用 ${this.data.summary.unchangedCount} 人，超限 ${this.data.summary.exceededCount} 人`, confirmText: '确认发布', success: ({ confirm }) => resolve(confirm), fail: () => resolve(false) })); if (!confirmed) return; this.setData({ publishing: true }); try { const draft = await valuationsApi.saveDraft(this.data.teamId, { windowId: this.data.workspace.window.id, expectedVersion: this.data.workspace.submission?.version ?? 1, items: this.data.players.map((player) => ({ snapshotId: player.snapshotId, proposedValueMinor: Number(player.inputValue) })) }); const submission = await valuationsApi.publish(this.data.teamId, { windowId: this.data.workspace.window.id, expectedVersion: draft.version }, `${Date.now()}-${Math.random()}`); this.setData({ workspace: { ...this.data.workspace, submission }, submissionCopy: submission.status === 'PENDING_REVIEW' ? '待管理员整批审核' : '已自动生效', editable: false }); wx.showToast({ title: '已发布', icon: 'success' }) } catch { wx.showToast({ title: '发布失败，请重试', icon: 'none' }) } finally { this.setData({ publishing: false }) } },
  localError() { if (!this.data.summary.complete || !this.data.workspace) return '请填写全部球员身价'; for (const player of this.data.players) { const error = validateValuationInput(player.inputValue); if (error) return `${player.playerName}：${error}`; const parsed = Number(player.inputValue); const rule = this.data.workspace.window.rule; if (parsed < rule.minimumValueMinor || parsed > rule.maximumValueMinor) return `${player.playerName}：身价必须在全局范围 ${rule.minimumValueMinor} — ${rule.maximumValueMinor} 内` } return null },
})
