import { Alert, Button, Descriptions, Drawer, Form, Input, InputNumber, Radio, Tag } from 'antd';
import { useEffect, useMemo, useState } from 'react';
import { RosterMutationResponseSchema, RosterPlayerCandidateListResponseSchema, type RosterEntry, type RosterPlayerCandidate } from '@efm/contracts';
import { adminApi, type AdminApi } from '../lib/api';
import { useMutationKey } from '../lib/mutation-key';

export function UpgradeCardDrawer({ open, leagueId, seasonId, entry, currentSalaryMinor, salaryCapMinor, api = adminApi, onClose, onCompleted }: { open: boolean; leagueId: string; seasonId: string; entry: RosterEntry | null; currentSalaryMinor: number; salaryCapMinor: number; api?: AdminApi; onClose(): void; onCompleted(): void }) {
  const [candidate, setCandidate] = useState<RosterPlayerCandidate | null>(null); const [cardId, setCardId] = useState<string>(); const [amountMinor, setAmount] = useState<number | null>(null); const [reason, setReason] = useState(''); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const key = useMutationKey();
  useEffect(() => { if (!open || !entry) return; void api.request(`/v1/admin/roster/leagues/${leagueId}/player-candidates?keyword=${encodeURIComponent(entry.playerName)}`, { schema: RosterPlayerCandidateListResponseSchema }).then((result) => { const player = result.items.find((item) => item.playerId === entry.playerId) ?? null; setCandidate(player); setCardId(player?.recommendedPlayerCardId ?? undefined); }).catch(() => setError('球员卡加载失败')); }, [api, entry, leagueId, open]);
  const selected = useMemo(() => candidate?.cards.find((card) => card.id === cardId), [candidate, cardId]); const projected = selected?.salaryMinor === null || selected?.salaryMinor === undefined || !entry ? null : currentSalaryMinor - entry.salaryMinor + selected.salaryMinor;
  const submit = async () => { if (!entry || !cardId || !reason.trim()) return; setBusy(true); setError(null); try { await api.request('/v1/admin/roster/card-upgrades', { method: 'POST', schema: RosterMutationResponseSchema, body: { seasonId, ownershipId: entry.id, newPlayerCardId: cardId, amountMinor, reason: reason.trim(), expectedVersion: entry.version, idempotencyKey: key.current() } }); key.reset(); onCompleted(); onClose(); } catch { setError('升级失败，请检查自动加点总评工资、工资帽和窗口权限'); } finally { setBusy(false); } };
  return <Drawer open={open} onClose={onClose} title={`卡片升级 · ${entry?.playerName ?? ''}`} size="large">{error ? <Alert role="alert" type="error" title={error} /> : null}<Radio.Group value={cardId} onChange={(event) => { setCardId(event.target.value); key.reset(); }}>{candidate?.cards.filter((card) => card.id !== entry?.currentPlayerCardId).map((card) => <Radio key={card.id} value={card.id} disabled={card.maxOverall === null}>{card.cardName} · 自动加点总评 {card.maxOverall ?? '—'} {card.recommended ? <Tag color="success">推荐</Tag> : null}</Radio>)}</Radio.Group>{selected ? <Descriptions column={2} items={[{ key: 'salary', label: '新卡工资', children: selected.salaryMinor ?? '未配置' }, { key: 'impact', label: '升级后球队工资', children: projected === null ? '—' : `${projected}/${salaryCapMinor}` }]} /> : null}<Form layout="vertical"><Form.Item label="升级费用（可不填）"><InputNumber min={1} precision={0} value={amountMinor} onChange={(value) => { setAmount(value); key.reset(); }} /></Form.Item><Form.Item label="操作原因"><Input value={reason} onChange={(event) => { setReason(event.target.value); key.reset(); }} /></Form.Item></Form><Button aria-label="确认升级" type="primary" loading={busy} disabled={!selected || selected.maxOverall === null || selected.salaryMinor === null || (projected ?? Infinity) > salaryCapMinor} onClick={() => void submit()}>确认升级</Button></Drawer>;
}
