import { Alert, Button, Card, Input, Modal, Select, Space, Table, Tag } from 'antd';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { ValuationSubmissionDetailSchema, ValuationSubmissionListResponseSchema, type ValuationSubmissionDetail } from '@efm/contracts';
import { adminApi, type AdminApi } from '../lib/api';
import { useMutationKey } from '../lib/mutation-key';

const labels = { DRAFT: '草稿', PUBLISHED: '已自动生效', PENDING_REVIEW: '待审核', APPROVED: '已通过', REJECTED: '已驳回' } as const;

export function ValuationReviewsPage({ api = adminApi }: { api?: AdminApi }) {
  const { leagueId = '' } = useParams(); const [items, setItems] = useState<ValuationSubmissionDetail[]>([]); const [status, setStatus] = useState('ALL'); const [windowId, setWindowId] = useState('ALL'); const [teamId, setTeamId] = useState('ALL'); const [review, setReview] = useState<{ item: ValuationSubmissionDetail; action: 'approve' | 'reject' } | null>(null); const [reason, setReason] = useState(''); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const key = useMutationKey();
  const load = useCallback(async () => { try { setItems((await api.request(`/v1/admin/leagues/${leagueId}/valuation-submissions`, { schema: ValuationSubmissionListResponseSchema })).items); } catch { setError('身价审核数据加载失败'); } }, [api, leagueId]); useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => items.filter((item) => (status === 'ALL' || item.status === status) && (windowId === 'ALL' || item.windowId === windowId) && (teamId === 'ALL' || item.leagueTeamId === teamId)), [items, status, teamId, windowId]);
  const submit = async () => { if (!review || !reason.trim()) return; setBusy(true); try { await api.request(`/v1/admin/valuation-submissions/${review.item.id}/${review.action}`, { method: 'POST', headers: { 'Idempotency-Key': key.current() }, schema: ValuationSubmissionDetailSchema, body: { expectedVersion: review.item.version, reason: reason.trim() } }); key.reset(); setReview(null); setReason(''); await load(); } catch { setError('审核提交失败，请刷新后重试'); } finally { setBusy(false); } };
  const windows = [...new Map(items.map((item) => [item.windowId, item.windowName])).entries()]; const teams = [...new Map(items.map((item) => [item.leagueTeamId, item.teamName])).entries()];
  return <Card className="valuation-review-card" title="身价整批审核台">{error ? <Alert role="alert" type="warning" title={error} /> : null}<Alert type="info" showIcon title="审核以整批为单位" description="查看每名球员的变化与越界原因后，只能整批通过或整批驳回，不支持逐球员修改。" /><Space wrap className="valuation-filters"><Select aria-label="审核状态" value={status} onChange={setStatus} options={[{ value: 'ALL', label: '全部状态' }, ...Object.entries(labels).map(([value, label]) => ({ value, label }))]} /><Select aria-label="申报窗口" value={windowId} onChange={setWindowId} options={[{ value: 'ALL', label: '全部窗口' }, ...windows.map(([value, label]) => ({ value, label }))]} /><Select aria-label="申报球队" value={teamId} onChange={setTeamId} options={[{ value: 'ALL', label: '全部球队' }, ...teams.map(([value, label]) => ({ value, label }))]} /></Space><Table scroll={{ x: 900 }} pagination={false} rowKey="id" dataSource={filtered} expandable={{ expandedRowRender: (row) => <Table pagination={false} rowKey="snapshotId" dataSource={row.items} columns={[{ title: '球员', dataIndex: 'playerName' }, { title: '原身价', render: (_, item) => item.baseValueMinor ?? '首次申报' }, { title: '申报身价', dataIndex: 'proposedValueMinor' }, { title: '允许范围', render: (_, item) => `${item.minimumAllowedMinor} — ${item.maximumAllowedMinor}` }, { title: '判定', render: (_, item) => item.exceedsRange ? <Tag color="error">超出范围</Tag> : <Tag color="success">合规</Tag> }]} /> }} columns={[{ title: '窗口', dataIndex: 'windowName' }, { title: '球队', dataIndex: 'teamName' }, { title: '状态', render: (_, row) => <Tag color={row.status === 'PENDING_REVIEW' ? 'warning' : row.status === 'APPROVED' || row.status === 'PUBLISHED' ? 'success' : 'default'}>{labels[row.status]}</Tag> }, { title: '提交人', dataIndex: 'submittedByDisplayName' }, { title: '球员数', render: (_, row) => row.items.length }, { title: '操作', render: (_, row) => row.status === 'PENDING_REVIEW' ? <Space><Button type="primary" onClick={() => setReview({ item: row, action: 'approve' })}>整批通过</Button><Button danger onClick={() => setReview({ item: row, action: 'reject' })}>整批驳回</Button></Space> : '—' }]} /><Modal open={review !== null} title={review?.action === 'approve' ? '确认整批通过' : '确认整批驳回'} okText="确认提交" cancelText="取消" confirmLoading={busy} okButtonProps={{ disabled: !reason.trim() }} onOk={() => void submit()} onCancel={() => setReview(null)}><label className="modal-field-label" htmlFor="review-reason">审核原因</label><Input.TextArea id="review-reason" value={reason} onChange={(event) => { setReason(event.target.value); key.reset(); }} maxLength={512} placeholder="请填写整批审核原因" /></Modal></Card>;
}
