import { Alert, Button, Card, Form, Input, InputNumber, Select, Space, Table, Tag } from 'antd';
import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import {
  LeagueSeasonSummarySchema, ValuationWindowListResponseSchema, ValuationWindowSchema,
  type ValuationWindow
} from '@efm/contracts';
import { z } from 'zod';
import { adminApi, type AdminApi } from '../lib/api';
import { useMutationKey } from '../lib/mutation-key';

type Fields = { name: string; startsAt: string; endsAt: string; minimumValueMinor: number; maximumValueMinor: number; maximumIncreaseBps: number; maximumDecreaseBps: number };
const initial: Fields = { name: '', startsAt: '', endsAt: '', minimumValueMinor: 0, maximumValueMinor: 100000, maximumIncreaseBps: 2000, maximumDecreaseBps: 2000 };
const states = { SCHEDULED: ['未开始', 'default'], OPEN: ['开放中', 'success'], CLOSED: ['已关闭', 'default'] } as const;

export function ValuationWindowsPage({ api = adminApi }: { api?: AdminApi }) {
  const { leagueId = '' } = useParams(); const [seasons, setSeasons] = useState<z.infer<typeof LeagueSeasonSummarySchema>[]>([]); const [seasonId, setSeasonId] = useState(''); const [windows, setWindows] = useState<ValuationWindow[]>([]); const [editing, setEditing] = useState<ValuationWindow | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [form] = Form.useForm<Fields>(); const key = useMutationKey();
  useEffect(() => { void api.request(`/v1/admin/leagues/${leagueId}/roster-seasons`, { schema: z.array(LeagueSeasonSummarySchema) }).then((items) => { setSeasons(items); setSeasonId(items[0]?.id ?? ''); }).catch(() => setError('赛季加载失败')); }, [api, leagueId]);
  const load = useCallback(async () => { if (!seasonId) return; try { setWindows((await api.request(`/v1/admin/seasons/${seasonId}/valuation-windows`, { schema: ValuationWindowListResponseSchema })).items); } catch { setError('身价窗口加载失败'); } }, [api, seasonId]);
  useEffect(() => { void load(); }, [load]);
  const save = async (values: Fields) => { if (!seasonId) return; setBusy(true); setError(null); try { const body = { name: values.name, startsAt: new Date(values.startsAt).toISOString(), endsAt: new Date(values.endsAt).toISOString(), rule: { minimumValueMinor: values.minimumValueMinor, maximumValueMinor: values.maximumValueMinor, maximumIncreaseBps: values.maximumIncreaseBps, maximumDecreaseBps: values.maximumDecreaseBps }, ...(editing ? { expectedVersion: editing.version } : {}) }; await api.request(editing ? `/v1/admin/valuation-windows/${editing.id}` : `/v1/admin/seasons/${seasonId}/valuation-windows`, { method: editing ? 'PATCH' : 'POST', headers: { 'Idempotency-Key': key.current() }, schema: ValuationWindowSchema, body }); key.reset(); setEditing(null); form.resetFields(); await load(); } catch { setError('保存失败，请检查时间和身价规则'); } finally { setBusy(false); } };
  const edit = (window: ValuationWindow) => { setEditing(window); key.reset(); form.setFieldsValue({ name: window.name, startsAt: window.startsAt.slice(0, 16), endsAt: window.endsAt.slice(0, 16), minimumValueMinor: window.currentRule.minimumValueMinor, maximumValueMinor: window.currentRule.maximumValueMinor, maximumIncreaseBps: window.currentRule.maximumIncreaseBps, maximumDecreaseBps: window.currentRule.maximumDecreaseBps }); };
  return <div className="workspace-grid valuation-workspace"><Card title="身价申报窗口">{error ? <Alert role="alert" type="warning" title={error} /> : null}<Select aria-label="选择赛季" value={seasonId || undefined} onChange={setSeasonId} options={seasons.map(({ id, displayName }) => ({ value: id, label: displayName }))} /><Table scroll={{ x: 920 }} pagination={false} rowKey="id" dataSource={windows} columns={[{ title: '窗口', dataIndex: 'name' }, { title: '状态', render: (_, row) => <Tag color={states[row.state][1]}>{states[row.state][0]}</Tag> }, { title: '时间范围', render: (_, row) => `${row.startsAt} — ${row.endsAt}` }, { title: '规则版本', render: (_, row) => `V${row.currentRule.version}` }, { title: '身价范围', render: (_, row) => `${row.currentRule.minimumValueMinor} — ${row.currentRule.maximumValueMinor}` }, { title: '涨/跌上限', render: (_, row) => `${row.currentRule.maximumIncreaseBps / 100}% / ${row.currentRule.maximumDecreaseBps / 100}%` }, { title: '操作', render: (_, row) => <Button type="link" onClick={() => edit(row)}>调整规则</Button> }]} /></Card><Card title={editing ? '调整窗口与发布新规则版本' : '新增身价窗口'}><Form<Fields> form={form} layout="vertical" initialValues={initial} onValuesChange={() => key.reset()} onFinish={(values) => void save(values)}><Form.Item label="窗口名称" name="name" rules={[{ required: true }]}><Input /></Form.Item><div className="inline-fields"><Form.Item label="开始时间" name="startsAt" rules={[{ required: true }]}><Input type="datetime-local" /></Form.Item><Form.Item label="结束时间" name="endsAt" rules={[{ required: true }]}><Input type="datetime-local" /></Form.Item></div><div className="inline-fields"><Form.Item label="最低身价" name="minimumValueMinor" rules={[{ required: true }]}><InputNumber min={0} precision={0} /></Form.Item><Form.Item label="最高身价" name="maximumValueMinor" rules={[{ required: true }]}><InputNumber min={0} precision={0} /></Form.Item></div><div className="inline-fields"><Form.Item label="最大涨幅（基点）" name="maximumIncreaseBps" rules={[{ required: true }]}><InputNumber min={0} max={10000} /></Form.Item><Form.Item label="最大跌幅（基点）" name="maximumDecreaseBps" rules={[{ required: true }]}><InputNumber min={0} max={10000} /></Form.Item></div><Alert type="info" showIcon title="修改规则会生成新版本，已保存的旧申报仍引用原规则。" /><Space><Button type="primary" htmlType="submit" loading={busy}>{editing ? '保存并发布新版本' : '创建窗口'}</Button>{editing ? <Button onClick={() => { setEditing(null); form.resetFields(); }}>取消</Button> : null}</Space></Form></Card></div>;
}
